# Использовать GLX (нужно для blur и прозрачности)
backend = "glx";

# Настройки Blur (размытия)
blur: {
  method = "dual_kawase";
  strength = 8;
  background = false;
  background-frame = false;
  background-fixed = false;
};

# Включаем VSync, чтобы не было разрывов
vsync = true;

# Важно: убираем старые параметры, на которые ругается picom
# (просто убедись, что строк "refresh-rate" и "type" с "c" здесь нет)

# Правила для окон
opacity-rule = [
  "65:class_g = 'Alacritty'",
  "65:class_g = 'Thunar'",
  "90:class_g = 'Google-chrome'"
];

# Радиус скругления углов (в пикселях)
corner-radius = 15;
# Исключения (если не хочешь скруглять панель или определенные окна)
rounded-corners-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "class_g = 'Polybar'",
  "class_g = 'i3-frame'"
];


# Позволяет композитору "отключаться" для любого окна, которое находится в режиме fullscreen
unredir-if-possible = true;

# (Опционально) Задержка перед отключением. 
# Можно оставить 0 для мгновенного эффекта, или поставить 200-500 мс, 
# если замечаешь "моргание" экрана при переключении окон.
unredir-if-possible-delay = 0; 

# Исключаем конкретно CS2, чтобы picom ее вообще не трогал
focus-exclude = [
    "class_g = 'cs2'"
];
