[colors]
background = #1a1b26
background-alt = #24283b
foreground = #c0caf5
primary = #7aa2f7
secondary = #bb9af7
alert = #f7768e
disabled = #565f89

[bar/mybar]
width = 96%
offset-x = 2%
offset-y = 5px
override-redirect = true
wm-restack = i3
height = 28pt
radius = 12
background = ${colors.background}
foreground = ${colors.foreground}
border-size = 2pt
border-color = ${colors.disabled}
line-size = 3pt
padding-left = 2
padding-right = 1
module-margin = 1
separator = |
separator-foreground = ${colors.disabled}

; Шрифты (убедись, что они установлены, или замени на свои)
font-0 = "JetBrainsMono Nerd Font:size=10;2"
font-1 = "Font Awesome 7 Free:style=Solid:size=13;4"
font-2 = "Font Awesome 7 Brands:size=11;2"
font-3 = "JetBrainsMono Nerd Font:size=16;4"

; Расположение модулей
modules-left = xworkspaces playerctl
modules-center = weather date
modules-right =  cpu gpu memory filesystem games-disk pulseaudio xkeyboard powermenu systray

cursor-click = pointer
enable-ipc = true

[module/xworkspaces]
type = internal/xworkspaces
label-active = %name%
label-active-background = ${colors.background-alt}
label-active-underline= ${colors.primary}
label-active-padding = 1
label-occupied = %name%
label-occupied-padding = 1
label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1
label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/arch-icon]
type = custom/text
content = "%{T4} %{T-}"
content-foreground = #1793d1
content-padding = 0
content-margin-right = 0
content-margin-left =  1

[module/powermenu]
type = custom/menu
expand-right = true
format-spacing = 1
label-open = "⏻"
label-open-foreground = #eceff4
label-close = "✕"
label-close-foreground = #bf616a
label-separator = |
label-separator-foreground = #4c566a
; Пункт: Перезагрузка
menu-0-0 = " Reboot "
menu-0-0-exec = menu-open-1
; Пункт: Выключение
menu-0-1 = "Shutdown "
menu-0-1-exec = menu-open-2
; Подменю подтверждения перезагрузки
menu-1-0 = " Cancel "
menu-1-0-exec = menu-open-0
menu-1-1 = " Reboot "
menu-1-1-exec = systemctl reboot
; Подменю подтверждения выключения
menu-2-0 = " Power Off "
menu-2-0-exec = systemctl poweroff
menu-2-1 = " Cancel "
menu-2-1-exec = menu-open-0

[module/systray]
type = internal/tray
format-margin = 2pt
tray-spacing = 4pt

[module/playerctl]
type = custom/script
exec = /home/denis/.config/polybar/playerctl.sh
interval = 0.5

[module/pulseaudio]
type = internal/pulseaudio
format-volume-prefix = " "
;format-volume-prefix-foreground = #900020
format-volume = <label-volume>
label-volume = %percentage%%
label-muted = muted
label-muted-foreground = ${colors.disabled}
label-foreground = #ffff

[module/filesystem]
type = internal/fs
interval = 30
mount-0 = /
format-mounted-prefix = " "
;format-mounted-prefix-foreground = #94e2d5
label-mounted = %free%
warn-percentage = 90
format-warn-prefix = "LOW DISK "
format-warn-prefix-foreground = ${colors.alert}
label-warn = %free%
label-warn-foreground = ${colors.alert}
;label-foreground = #94e2d5

[module/games-disk]
type = internal/fs
interval = 30
; Попробуй указать путь без финального слеша
mount-0 = /mnt/Games
; Этот параметр заставляет Polybar четко следовать списку mount-n
fixed-values = true
format-mounted-prefix = "  "
;format-mounted-prefix-foreground = #cba6f7
label-mounted = %free%
; Если диск не виден, выведет это (поможет понять, в чем проблема)
label-unmounted = "GAMES: OFF"
label-unmounted-foreground = ${colors.disabled}
;label-foreground = #cba6f7

[module/memory]
type = custom/script
exec = ~/.config/polybar/mem-exact.sh
interval = 1
format-prefix = " "
;format-prefix-foreground = #ffb52a
label = %output%
click-left = alacritty -e btop
;label-foreground = #ffb52a

[module/gpu]
type = custom/script
exec = ~/.config/polybar/gpu.sh
interval = 2
format-prefix = " "
format = <label>
label = %output%
;label-foreground = ${colors.primary}


[module/cpu]
type = internal/cpu
interval = 2
format-prefix = " "
;format-prefix-foreground = #f38ba8
label = %percentage%%
;label-foreground = #f38ba8

[module/temperature]
type = internal/temperature
interval = 1
thermal-zone = 0
warn-temperature = 70
format = <label>
format-prefix = " "
;format-prefix-foreground = #f38ba8
label = %temperature-c%
;label-foreground = #f38ba8

[module/weather]
type = custom/script
exec = curl -s "https://wttr.in/Almetyevsk?format=%t" | tr -d '+'
interval = 1800
format-prefix = "  "
;format-prefix-foreground = #f9e2af
label = %output%
;label-foreground = #f9e2af

[module/date]
type = internal/date
interval = 1
format-prefix = " "
;format-prefix-foreground = #ffffff
date = %H:%M
date-alt = %Y-%m-%d %H:%M:%S
label = %date%
;label-foreground = #ffffff

[module/xkeyboard]
type = internal/xkeyboard
; Список языков, которые нужно игнорировать (необязательно)
blacklist-0 = num lock
blacklist-1 = scroll lock
blacklist-2 = caps lock
; Иконка перед обозначением языка
format-prefix = "󰌌 "
;format-prefix-foreground = ${colors.primary}
; Оформление (фон и линия снизу)
;format-background = ${colors.background-alt}
format-padding = 1
;format-underline = ${colors.primary}
; Как отображать сам текст (RU / EN)
label-layout = %layout%
;label-layout-foreground = ${colors.foreground}
; Цвет для индикаторов (например, если Caps Lock включен)
label-indicator-padding = 2
label-indicator-margin = 1
;label-indicator-foreground = ${colors.background}
;label-indicator-background = ${colors.secondary}

[settings]
screenchange-reload = true
pseudo-transparency = true
compositing-background = source
